server:
  servlet:
    context-path: /file-management/api/

spring:
  profiles:
    active: ${ACTIVE_PROFILE:}
  application:
   name: file-management-service

app:
  file-storage:
    path: ${FILE_STORAGE_PATH:${user.dir}/files}

logging:
  level:
    web: info
    root: info
